[package]
name = "greeting"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.3"
serde = "1.0.133"
actix-rt = "2.6.0"
actix-cors = "0.5.4"
serde_json = "1.0"
futures = "0.3"